### ISSUE TITLE
Create a new database handle by DataSource

### ISSUE THREAD

**Issue by raderio** [JDBDT/jdbdt#47]
In Spring we already have DataSource instance https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html

Can you please add one more method to create a new database handle, like`DB database(DataSource dataSource)` into `class JDBDT`

**Comment by edrdo** [comment]
This shorthand method will be easy to add in the next release (in a few days). Meanwhile, in the current version you should be able to simply use `database(ds.getConnection())` i.e. by using https://docs.oracle.com/javase/8/docs/api/javax/sql/DataSource.html#getConnection--

**Comment by raderio** [comment]
Thanks

**Comment by edrdo** [comment]
@raderio 1.2.0 has been released. Please let me know of any issues.
