### ISSUE TITLE
Populate database with data set vararg

### ISSUE THREAD

**Issue by raderio** [JDBDT/jdbdt#48]
In our use case we have predefined data sets, so we need to call
```
JDBDT.populate(predefinedUsers);
JDBDT.populate(predefinedEvents);
JDBDT.populate(predefinedPosts);
```
Maybe will be more useful to allow `populate` receive vararg of DataSet
`populate(DataSet... dataSets)`
so will be possible to call
`JDBDT.populate(predefinedUsers, predefinedEvents, predefinedPosts)`

**Comment by edrdo** [comment]
Yes this will be easy to add in the next release (1.1.3). 
A workaround (for now) is easy of course: 
     
     void populateVariousTables(DataSets ... dataSets) {
         for (DataSet ds : dataSets) { 
            populate(ds);
         }
     }

**Comment by edrdo** [comment]
This issue is subsumed by #52.
