### ISSUE TITLE
How to assert a table data was not changed

### ISSUE THREAD

**Issue by raderio** [JDBDT/jdbdt#49]
Our flow is:
- before each test delete all data
- than insert users in users table
- call some methods, test logic
- assert data was not changed

```
DB db = ... ;
Table t = table("USERS")
         .columns("ID", "LOGIN", "NAME", "PASSWORD", "CREATED")
         .build(db);
DataSet users
   = data(t)
    .row(0,   "root",  "Root User",  "god",       null)
    .row(101, "john",  "John Doe",   "justDoeIt", Date.valueOf("2014-07-12"));
```

It is not clear how to assert a table data was not changed.
Can you show an example?

**Comment by raderio** [comment]
As I understand we should use
`JDBDT.assertUnchanged(accounts.getSource())`
If this is correct can you please update documentation?
http://jdbdt.org/DBAssertions.html
Please add/modify
```
// [1] Populate a table with some data.
Table t = ...;
DataSet data = data(t). ...;
populate(data); // --> 'data' becomes the reference snapshot
// add next line in docs
data.getSource(); // to get the snapshot
```

**Comment by edrdo** [comment]
I don't understand your doubt.  You only need `assertUnchanged(t)` in your example, you don't need to get the snapshot back (?).

You may check the JDBDT tutorial for other examples - http://jdbdt.org/Tutorial.html and the corresponding code here on GitHub.

**Comment by edrdo** [comment]
For instance in the JDBDT tutorial code you have the following test:
```
@Test
public void testNonExistingUserDelete() throws SQLException {
    User u = nonExistingUser();
    boolean deleted = theDAO.deleteUser(u);    
    assertUnchanged("No DB changes", theTable);
    assertFalse("return value", deleted);
}
```
