### ISSUE TITLE
Add possibility to take snapshot for multiple tables at once

### ISSUE THREAD

**Issue by raderio** [JDBDT/jdbdt#50]
Will be useful to take snapshot for multiple tables at once.

It is useful when a test do not change nothing in database because user perform an invalid operation, so in this case at the end of the test we should be able to assert that tables was not changed, so we just check the snapshot.

**Comment by raderio** [comment]
Also, will be useful to take snapshot of all tables with possibility to specify what tables to exclude.

**Comment by edrdo** [comment]
Hmm ... that's interesting but a little more tricky, as it may  be dependent on database engine internals. I try to stay away from these :) Apart from some [known issues ](http://jdbdt.org/Compatibility.html), the API works the same for a relevant set of mainstream database engines.

**Comment by edrdo** [comment]
This issue is subsumed by #52
