### ISSUE TITLE
Can not escape commas in csv-format datasets

### ISSUE THREAD

**Issue by LiashenkoVitalii** [JDBDT/jdbdt#68]
I found out that when we try to read a dataset from csv file using comma as values separator there is no chance to escape comma in fields. But I didn't manage to find out how to escape comma when we need it from the documentation.
For example, the string  "apples, carrots, and oranges" will be read as three separate values as well as the string "apples\, carrots\, and oranges". 
So, is there some way to escape comma like it is described [here](https://www.csvreader.com/csv_format.php) or [here](https://www.ietf.org/rfc/rfc4180.txt)?

**Comment by edrdo** [comment]
Escape sequences are not supported by the current release.  This should be easy to add in the next release though. The possible (and fragile) workaround I would suggest is to use a [different separator in your input files](http://jdbdt.org/apidocs/org/jdbdt/CSV.Format.html#separator-java.lang.String) (e.g. it may be another character different from comma or a sequence of characters).

**Comment by LiashenkoVitalii** [comment]
Thanks for your quick reply

**Comment by edrdo** [comment]
@LiashenkoVitalii A release candidate (1.4.0-RC1) is now available (Maven Central, pre-release at GitHub) where CSV support should now conform to [RFC-4180](https://www.ietf.org/rfc/rfc4180.txt) except for the possibility of having new lines or carriage returns within escaped sequences (e.g. `"a,b,c"` will be ok but not `"a,b<newline>,c"`). Please let me know if this is working for you. The 1.4.0 final release should be out soon.

**Comment by edrdo** [comment]
Version 1.4.0 has been released.
