### ISSUE TITLE
Be able to read data in spock-like table format

### ISSUE THREAD

**Issue by drmaas** [JDBDT/jdbdt#70]
For example:

col1 || col2 || col3
val1 | val2  | val3
val1 | val2  | val3
val1 | val2  | val3

This would be make data files very easy to read - even easier than reading CSV, as it would look more like a table of values.

**Comment by edrdo** [comment]
@drmaas The current support for CSV may allow you to read this type of files, e.g. in the example above, use   [separator('|')](http://jdbdt.org/apidocs/org/jdbdt/CSV.Format.html#separator-char-) and [`hasHeader()` ](http://jdbdt.org/apidocs/org/jdbdt/CSV.Format.html#hasHeader--) to skip the first line. White space won't be trimmed though, I guess it does make sense to have an option for that in a future version, but for now make sure it is trimmed between uses of the separator character. That being said,  there are no plans to support other formats beyond CSV (Spock-like or JSON, XML, etc). A core motivation for JDBDT is to avoid the need for external data files as much as possible through the  programmatic definition of data sets  (see http://jdbdt.org/DataSets.html  and http://jdbdt.org/DBSetup.html). CSV file support was added later acknowledging the convenience of data set files in many cases,  but I do not wish to shift the focus of JDBDT with additional support for other file formats. I'll close this issue at least for now.
