### ISSUE TITLE
Consider workaround for Oracle JDBC driver getObject(..) returning oracle.sql.TIMESTAMP 

### ISSUE THREAD

**Issue by imps-od** [JDBDT/jdbdt#72]
When comparing datasets from Oracle tables to stored CSV files with expected data, I noticed that the `getObject(..)` methods on result sets from the Oracle JDBC driver return `oracle.sql.TIMESTAMP`, not `java.sql.Timestamp`.

This leads to  `assertEquals(..)` failing because the different timestamp objects are not equal, even when they represent the same point in time.

A workaround according to [this discussion](https://community.oracle.com/tech/developers/discussion/349145/getobject-returns-oracle-sql-timestamp-instead-of-java-sql-timestamp) would be to use `getTimeStamp(..`) instead of `getObject(..)` for the TIMESTAMP JDBC type. This could be handled by a code change in `org.jdbdt.DataSource#proceedWithQuery`.

**Comment by edrdo** [comment]
Hmmm ... this may be tricky, I fear that changing `proceedWithQuery` in a "type-dependent" way (and other parts) may raise issues with other engines, and I wish to avoid "type-dependent" code as much as possible. So, a method like `takeSnapshot` returns `TIMESTAMP` values whereas `read` returns `java.sql.Timestamp` values from CSV files. The way forward should be to allow for user-defined input conversions in conjunction with `CSV.Format` (overriding the default ones; this is already "type-dependent" code anyway). I will get back to this later.

**Comment by imps-od** [comment]
Being able to override the CSV type conversions would certainly be useful.

**Comment by imps-od** [comment]
Our current workaround is to write the Oracle dataset to a temporary csv file, read it back and then do the `assertEquals(..)` against the dataset read from the stored CSV file that contains the expected data. 

This works and protects us even from the other issue regarding BigDecimal values that you fixed on HEAD. 

Something like this:
```
final Table table = table(tableName).columns(columnNames).build(db);

final File csvTempFile = getTempFile(type);
write(takeSnapshot(table), csv, csvTempFile);
final DataSet actualData = read(table, csv, csvTempFile);

final File csvFile = getCsvFile(csvFileDir, type);
final DataSet expectedData = read(table, csv, csvFile);

JDBDT.assertEquals(tableName  + " dataset verification", expectedData, actualData);
```

**Comment by edrdo** [comment]
The workaround you mentioned works because `useReadConversions()` is not called, implying that no conversions are performed (data fields will all have `String` type). 

The HEAD commit mentioned above puts forward method `Format.overrideConversion()`,  allowing you to specify a custom conversion for a given JDBC type, i.e., in your case something like:

```
import java.sql.JDBCType;
import oracle.sql.TIMESTAMP;
... 
Format f = ... .useReadConversions().overrideConversion(JDBCType.TIMESTAMP,  s -> new TIMESTAMP(s));
```

See if this works for you ...   (I had no time to test it thoroughly; unit tests still do not cover this functionality properly).

**Comment by imps-od** [comment]
I saw your commit. Looks promising. Thanks! Will try it out tomorrow.

**Comment by imps-od** [comment]
I tried the suggested override, but it turns out that the `oracle.sql.TIMESTAMP` class does not implement `equals(..)` which means that it inherits `equals(..)` from `java.lang.Object`, which checks for object reference identity and of course that is never true in the dataset comparison. 

So it looks like this is a dead-end and I will stick to our "compare temporary csv from actual data to stored csv containing expected data" approach.

For the record, I used a CSV setup like this:
```
private final Format csv = new Format().hasHeader().alwaysEscapeOutput().useReadConversions()
		.overrideConversion(JDBCType.TIMESTAMP, oracle.sql.TIMESTAMP::new);
```

I guess this effectively also means that Oracle dataset to Oracle dataset deltas could have unexpected results for other JDBDT users as well, even if they don't use CSV at all. Your Delta logic depends on Row hash codes and Row equality, using `Arrays.deepHashCode()` and `Arrays.deepEquals(..)` which will fail for column values that do not have proper `equals(..)` - and matching `hashCode(..)` - implementation. 

Oracle is obviously a very commonly used database engine and has had that quirky getObject(..) behaviour for a long time now and will likely not change it. Whereas `rs.getTimestamp(..)` returns `java.sql.Timestamp` as defined in `java.sql.Resultset` [javadoc](https://docs.oracle.com/javase/8/docs/api/java/sql/ResultSet.html#getTimestamp-int-), and all JDBC compliant engines and drivers have to adhere to that.

So maybe column type specific reading from the result set would actually be more robust and consistent across database engines?

I am saying all this as personal opinion, not as urgent request. We have a work-around as mentioned above and are happy for now. Thanks for the great work you do and the impressive responsiveness in maintaining this library.

Obrigado!

**Comment by edrdo** [comment]
> I tried the suggested override, but it turns out that the oracle.sql.TIMESTAMP class does not implement equals(..) which means that it inherits equals(..) from java.lang.Object,  [...] Your Delta logic depends on Row hash codes and Row equality, using Arrays.deepHashCode() and Arrays.deepEquals(..) which will fail for column values that do not have proper equals(..) - and matching hashCode(..) - implementation.

Damn :( 

>Oracle is obviously a very commonly used database engine and has had that quirky getObject(..) behaviour for a >long time now and will likely not change it. Whereas rs.getTimestamp(..) returns java.sql.Timestamp as defined in 
> java.sql.Resultset javadoc, and all JDBC compliant engines and drivers have to adhere to that.
>So maybe column type specific reading from the result set would actually be more robust and consistent across >database engines?

It's possible, but I'll have to check this  in depth.  It's hard to bet on JDBC strict compatibility and homogeneous behavior by assorted database engines ... :(

I'll keep the `overrideConversion()` feature in any case. It will be part of release 1.4.1, due in a few days in principle along with the fix for #71.  But  I'll close this issue otherwise for now.

**Comment by imps-od** [comment]
Additional info: I verified the described behaviour of `getObject(..)` for following Oracle JDBC driver version:
```
<dependency>
	<groupId>com.oracle.database.jdbc</groupId>
	<artifactId>ojdbc8</artifactId>
	<version>21.3.0.0</version>
</dependency>
```
I also saw it with `ojdbc6`.

**Comment by edrdo** [comment]
Thanks

**Comment by edrdo** [comment]
@impoldo1  Version 1.4.1 has been released.
